default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_PRIVATE_KEY'], # base64-encoded contents of the .p8 key
      is_key_content_base64: true
    )

    increment_build_number(xcodeproj: "RelationshipCheckin.xcodeproj")

    build_app(
      xcodeproj: "RelationshipCheckin.xcodeproj",
      scheme: "RelationshipCheckin",
      export_method: "app-store",
      clean: true,
      include_bitcode: false,
      output_directory: "build",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false
    )
  end
end


